name: Laravel GPR Publish

on:
  push:
    branches:
      - main

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: composer install --no-dev
      - name: Create package directory
        run: mkdir my-package
      - name: Build and publish package
        run: |
          php artisan package:discover
          tar -czvf my-package.tar.gz my-package
          curl -v \
            -X PUT \
            -H "Content-Type: application/octet-stream" \
            -H "Authorization: Bearer ${{ secrets.PAT }}" \
            --data-binary @my-package.tar.gz \
            "https://uploads.github.com/repos/${{ github.repository }}/packages/laravel/my-package/${{ github.sha }}/my-package.tar.gz"
      - name: Publish package
        run: npm publish --access public
