name: Publish Laravel Package

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'
        extensions: mbstring, pdo_mysql
    - name: Install dependencies
      run: composer install
    - name: Build package
      run: php artisan package:discover && php artisan package:discover
    - name: Login to GitHub Packages
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.PAT }}
    - name: Publish to GitHub Packages
      uses: docker/build-push-action@v2.7.0
      with:
        context: .
        push: true
        tags: ghcr.io/technodroidz/extapp:latest
        registry: ghcr.io
