name: Publish Laravel Package

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'
        extensions: mbstring, pdo_mysql
    - name: Install dependencies
      run: composer install
    - name: Build package
      run: php artisan package:discover && php artisan packager:build
    - name: Publish to GitHub Packages
      uses: docker://ghcr.io/docker/build-push-action:v2.8.2
      with:
        context: ./
        push: true
        tags: ${{ github.repository }}:latest
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
